spring:
  application:
    name: concert-reservation
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:concert
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show_sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org:
      hibernate:
        SQL: debug
      hibernate.type:
        descriptor.sql.BasicBinder: trace

reservation:
  expireMinutes: 5 # 임시배정 유효 시간(분)
  expireCheckRate: 60000 # 만료 체크 주기(ms)
  syncAvailableSeatsRate: 60000 # 예약 가능 좌석 수 동기화 주기(ms)

waiting-queue:
  activateRate: 6000 # 대기열 활성화 체크 주기(ms)
  expireCheckRate: 6000 # 만료 체크 주기(ms)
  activeUsers: 2 # 활성화할 최대 유저 수
  expireMinutes: 5 # 대기열 유효 시간(분)
